name: Kiem-Thu-Tu-Dong-CI

# Kích hoạt bot mỗi khi có ai đó đẩy code lên nhánh main
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Chạy trên máy chủ ảo của GitHub

    steps:
    - name: Tải mã nguồn về máy chủ
      uses: actions/checkout@v3

    - name: Cài đặt môi trường Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cài đặt thư viện (Jest)
      run: npm install

    - name: Chạy kiểm thử tự động (Unit Test)
      run: npm test